### ISSUE TITLE
EID discovery with external data-plane

### ISSUE THREAD

**Issue by Bystrykha** [farinacci/lispers.net#25]
Hello, Dino!
I found the only place where discovery ipc message sends from ITR is this (xtr.go):
![image](https://github.com/farinacci/lispers.net/assets/59131326/832b6f98-7224-4be9-ae3e-0571a10e0c0b)

I have a question: if dynamic EID changes xTR, how we suppose to register it with "rloc == nil" ?
As far as I understood, this will trigger map-request, but not Map-register.

**Comment by farinacci** [comment]
> Hello, Dino!

Hi Alexey. Glad you are reading code!

> I found the only place where discovery ipc message sends from ITR is this (xtr.go):

Well that piece of code:




is simply a map-cache lookup. And its in all the ITR related data-planes we implemented.

As for dyn-EID discovery. If a new source that is in an dynamic-EID block sends a packet, the ITR needs to discover it regardless of the destination EID the new source is sending to.

So before a map-cache lookkup a source-EID check is performed. And that is when a dynamic-EID check is performed. At that point the lisp-itr process will send an IPC message to the lisp-etr process so a Map-Register can be sent to the mapping system for the new dyn-EID discovered.

> I have a question: if dynamic EID changes xTR, how we suppose to register it with "rloc == nil" ?

That is a configuration change. It has not relation to the "rloc == nil" check. That check simply indicates that the map-cache lookup failed to produce an RLOC. Meaning the longest-match lookup did not find any entry.

Dino

**Comment by Bystrykha** [comment]
Ok, but I still don't see where the dynamic-EID presence timer for the control plane (LISP_DEFAULT_DYN_EID_TIMEOUT (15 seconds)) is being updated. I was waiting for some kind of IPC message that would notify the control plane about the activity of dynamic-EID, but did not find anything ...

**Comment by farinacci** [comment]
> Ok, but I still don't see where the dynamic-EID presence timer for the control plane (LISP_DEFAULT_DYN_EID_TIMEOUT (15 seconds)) is being updated. I was waiting for some kind of IPC message that would notify the control plane about the activity of dynamic-EID, but did not find anything ...

When the dyn-EID is discovered a timestamp is stored. Then LISP_DEFAULT_DYN_EID_TIMEOUT is tested in lisp_itr_timeout_dynamic_eids().

Dino

**Comment by Bystrykha** [comment]
Ok, I'll keep that in mind, thanks!
